spring.application.name=tap

# Database Configuration
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=

# H2 Console Configuration
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Initialization
spring.jpa.defer-datasource-initialization=true
spring.sql.init.encoding=UTF-8
